    # Question 21
    # Evaluate the sum of all amicable numbers under 10,000

def sum_of_proper_fact(x):
    # This function takes x as an argument and returns the sum
    # of all of x's proper factors

    counter = 1
    proper_factors = []
    for item in range(2,int(x**.5)+1):
        if x % item == 0:
            proper_factors.append(item)
            proper_factors.append(x/item)
    proper_factors.append(1)
    answer = sum(proper_factors)
    return answer

def lister(limit):
    # This function creates a list of numbers from 1 to and excluding limit
    # and each number's sum of proper factors.
    # It returns a list of two element lists.

    counter = 1
    big_list = []
    while counter < limit:
        element1 = counter
        element2 = sum_of_proper_fact(counter)
        big_list.append([element1, element2])
        counter += 1
    for index, item in enumerate(big_list):
        if item[0] == item[1]:
            del big_list[index]
    return big_list

def sum_of_AN(limit):
    # Compares the list generated by lister() with a list where the element lists are flipped,
    # creates a list of amicable numbers, and then summs them.
    list1 = lister(limit)
    list2 = []
    for item in list1:
        list2.append(item[::-1])
    list3 = [i for i in list1 if i in list2]
    list4 = []
    for item in list3:
        list4.append(item[0])
    return sum(list4)
    
print(sum_of_AN(10000))

